# Generated by Django 3.1.3 on 2020-11-21 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DangerMap', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EvacuaionSite',
            new_name='EvacuationSite',
        ),
    ]
